### PR TITLE
Minor doc cleanups, removed lint warnings

### PR DESCRIPTION
**Pull request by jaseemabid**
Commits are tiny and self explanatory.

### CODE REVIEW

**Comment by berzniz** [comment]
Thanks for the fixes!

I do not want to include the "Clean up some lint errors" commit. I do not like the coding-style it uses and the last snippet is taken directly from the backbonejs source code.

Please resubmit the pull request with only the first two commits and I'll gladly merge them.

**Comment by jaseemabid** [comment]
No probs! What about `key === null` ?

**Comment by berzniz** [comment]
What happens if `keys` is `undefined`?

A quick note:
`undefined == null // true`
`undefined === null // false`

In the original it will still match the comparison, but with this change it will not.

I'm not sure I want to introduce this kind of change.

What are your thoughts?

**Comment by shovon** [comment]
@jaseemabid are you using JSHint? If so, add the following absolutely at the top of the file:

``` javascript
/* jshint eqnull */
```

No checks of `somevar == null` will throw any errors, now.

**Comment by jaseemabid** [comment]
Maybe you should just merge the 2 commits now

**Pull request closed without merging**
